name: Deploy Portfolio to S3
# 1. THE TRIGGER: When does this run?
on:
  push:
    branches:
      - main
  workflow_dispatch:  # <--- Add this exact line right here!

# Tell GitHub to use the modern Node 24 runtime
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

# 2. THE JOB: What server are we using?
jobs:
  deploy:
    runs-on: ubuntu-latest

    # 3. THE STEPS: What exactly are we doing?
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Boto3
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Run deployment script
        run: python deploy.py